# Generated by Django 4.1.4 on 2023-01-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_autor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biographi',
            new_name='Biography',
        ),
    ]
