# Generated by Django 4.1.4 on 2023-01-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_biographi_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='author',
        ),
    ]
